### ISSUE TITLE
sshpass in the container

### ISSUE THREAD

**Issue by romangr** [arillso/action.playbook#1]
Hello,

It seems like sshpass is not available in the image used to run ansible so it's impossible to use password to connect to the hosts from action.playbook. Was it done on purpose or maybe I'm doing something wrong?

Thanks,
Roman

**Comment by sbaerlocher** [comment]
Hello Roman

Thanks for the tip, since we only use ssh with SSH keys I didn't notice this. I have now corrected it in the underlying container. arillso/docker.ansible#8

**Comment by romangr** [comment]
@sbaerlocher Thank you!

**Comment by sbaerlocher** [comment]
sshpass is now integrated in releases 0.0.2
